define ->
  {
    UNSPECIFIED: 0
    SINGLE: 1
    DOUBLE: 2
    TRIPLE: 3
    QUADRUPLE: 4
    QUINTUPLE: 5
    HEXTUPLE: 6
    ONEANDAHALF: 7
    TWOANDAHALF: 8
    THREEANDAHALF: 9
    FOURANDAHALF: 10
    FIVEANDAHALF: 11
    AROMATIC: 12
    IONIC: 13
    HYDROGEN: 14
    THREECENTER: 15
    DATIVEONE: 16
    DATIVE: 17
    DATIVEL: 18
    DATIVER: 19
    OTHER: 20
    ZERO: 21
  }