define ->
  {
    "atoms": [{
      "atomicNumber": 0,
      "elementColor": [0.07, 0.5, 0.7],
      "exactMass": 0.0,
      "mass": 0.0,
      "name": "Dummy",
      "radiusCovalent": 0.0,
      "radiusVDW": 0.0,
      "symbol": "Xx"
    }, {
      "atomicNumber": 1,
      "boilingpoint": 20.28,
      "discoverers": "C. Cavendish",
      "discoveryCountry": "uk",
      "discoveryDate": "1766",
      "electronAffinity": 0.75420375,
      "electronegativityPauling": 2.2,
      "electronicConfiguration": "1s1",
      "elementColor": [1.0, 1.0, 1.0],
      "exactMass": 1.007825032,
      "family": "Non-Metal",
      "group": 1,
      "ionization": 13.5984,
      "mass": 1.00794,
      "meltingpoint": 14.01,
      "name": "Hydrogen",
      "nameOrigin": "Greek 'hydro' and 'gennao' for 'forms water'",
      "period": 1,
      "periodTableBlock": "s",
      "radiusCovalent": 0.37,
      "radiusVDW": 1.2,
      "symbol": "H"
    }, {
      "atomicNumber": 2,
      "boilingpoint": 4.216,
      "discoverers": ["P. J. Janssen", "J. N. Lockyer"],
      "discoveryCountry": ["se", "uk"],
      "discoveryDate": "1895",
      "electronAffinity": 0.0,
      "electronicConfiguration": "1s2",
      "elementColor": [0.85, 1.0, 1.0],
      "exactMass": 4.002603254,
      "family": "Noblegas",
      "group": 8,
      "ionization": 24.5874,
      "mass": 4.002602,
      "meltingpoint": 0.95,
      "name": "Helium",
      "nameOrigin": "The Greek word for the sun was 'helios'",
      "period": 1,
      "periodTableBlock": "p",
      "radiusCovalent": 0.32,
      "radiusVDW": 1.4,
      "symbol": "He"
    }, {
      "atomicNumber": 3,
      "boilingpoint": 1615.0,
      "discoverers": "A. Arfvedson",
      "discoveryCountry": "se",
      "discoveryDate": "1817",
      "electronAffinity": 0.618049,
      "electronegativityPauling": 0.98,
      "electronicConfiguration": "He 2s1",
      "elementColor": [0.8, 0.5, 1.0],
      "exactMass": 7.01600455,
      "family": "Alkali_Earth",
      "group": 1,
      "ionization": 5.3917,
      "mass": 6.941,
      "meltingpoint": 453.7,
      "name": "Lithium",
      "nameOrigin": "Greek 'lithos' means 'stone'",
      "period": 2,
      "periodTableBlock": "s",
      "radiusCovalent": 1.34,
      "radiusVDW": 2.2,
      "symbol": "Li"
    }, {
      "atomicNumber": 4,
      "boilingpoint": 3243.0,
      "discoverers": "Nicholas Louis Vauquelin",
      "discoveryCountry": "fr",
      "discoveryDate": "1797",
      "electronAffinity": 0.0,
      "electronegativityPauling": 1.57,
      "electronicConfiguration": "He 2s2",
      "elementColor": [0.76, 1.0, 0.0],
      "exactMass": 9.0121822,
      "family": "Alkaline_Earth",
      "group": 2,
      "ionization": 9.3227,
      "mass": 9.012182,
      "meltingpoint": 1560.0,
      "name": "Beryllium",
      "nameOrigin": "Greek 'beryllos' for 'light-green stone'",
      "period": 2,
      "periodTableBlock": "s",
      "radiusCovalent": 0.9,
      "radiusVDW": 1.9,
      "symbol": "Be"
    }, {
      "atomicNumber": 5,
      "boilingpoint": 4275.0,
      "discoverers": ["Louis Joseph Gay-Lussac", "Louis Jacques Thenard"],
      "discoveryCountry": ["uk", "fr"],
      "discoveryDate": "1808",
      "electronAffinity": 0.279723,
      "electronegativityPauling": 2.04,
      "electronicConfiguration": "He 2s2 2p1",
      "elementColor": [1.0, 0.71, 0.71],
      "exactMass": 11.0093054,
      "family": "Metalloids",
      "group": 3,
      "ionization": 8.298,
      "mass": 10.811,
      "meltingpoint": 2365.0,
      "name": "Boron",
      "nameOrigin": "Boron means 'Bor(ax) + (carb)on'. It is found in borax and behaves a lot like carbon",
      "period": 2,
      "periodTableBlock": "p",
      "radiusCovalent": 0.82,
      "radiusVDW": 1.8,
      "symbol": "B"
    }, {
      "atomicNumber": 6,
      "boilingpoint": 5100.0,
      "discoveryCountry": "ancient",
      "discoveryDate": "0",
      "electronAffinity": 1.262118,
      "electronegativityPauling": 2.55,
      "electronicConfiguration": "He 2s2 2p2",
      "elementColor": [0.5, 0.5, 0.5],
      "exactMass": 12.0,
      "family": "Non-Metal",
      "group": 4,
      "ionization": 11.2603,
      "mass": 12.0107,
      "meltingpoint": 3825.0,
      "name": "Carbon",
      "nameOrigin": "Latin 'carboneum' for carbon",
      "period": 2,
      "periodTableBlock": "p",
      "radiusCovalent": 0.77,
      "radiusVDW": 1.7,
      "symbol": "C"
    }, {
      "atomicNumber": 7,
      "boilingpoint": 77.344,
      "discoverers": "D. Rutherford",
      "discoveryCountry": "uk",
      "discoveryDate": "1772",
      "electronAffinity": -0.07,
      "electronegativityPauling": 3.04,
      "electronicConfiguration": "He 2s2 2p3",
      "elementColor": [0.05, 0.05, 1.0],
      "exactMass": 14.003074,
      "family": "Non-Metal",
      "group": 5,
      "ionization": 14.5341,
      "mass": 14.0067,
      "meltingpoint": 63.15,
      "name": "Nitrogen",
      "nameOrigin": "Latin 'nitrogenium' ('forms saltpeter')",
      "period": 2,
      "periodTableBlock": "p",
      "radiusCovalent": 0.75,
      "radiusVDW": 1.6,
      "symbol": "N"
    }, {
      "atomicNumber": 8,
      "boilingpoint": 90.188,
      "discoverers": "J. Priestley",
      "discoveryCountry": ["se", "uk"],
      "discoveryDate": "1774",
      "electronAffinity": 1.461112,
      "electronegativityPauling": 3.44,
      "electronicConfiguration": "He 2s2 2p4",
      "elementColor": [1.0, 0.05, 0.05],
      "exactMass": 15.99491462,
      "family": "Non-Metal",
      "group": 6,
      "ionization": 13.6181,
      "mass": 15.9994,
      "meltingpoint": 54.8,
      "name": "Oxygen",
      "nameOrigin": "Latin 'oxygenium' (forms acids)",
      "period": 2,
      "periodTableBlock": "p",
      "radiusCovalent": 0.73,
      "radiusVDW": 1.55,
      "symbol": "O"
    }, {
      "atomicNumber": 9,
      "boilingpoint": 85.0,
      "discoverers": "H. F. Moissan",
      "discoveryCountry": "fr",
      "discoveryDate": "1886",
      "electronAffinity": 3.4011887,
      "electronegativityPauling": 3.98,
      "electronicConfiguration": "He 2s2 2p5",
      "elementColor": [0.7, 1.0, 1.0],
      "exactMass": 18.99840322,
      "family": "Halogen",
      "group": 7,
      "ionization": 17.4228,
      "mass": 18.9984032,
      "meltingpoint": 53.55,
      "name": "Fluorine",
      "nameOrigin": "Latin 'fluere' ('floats')",
      "period": 2,
      "periodTableBlock": "p",
      "radiusCovalent": 0.71,
      "radiusVDW": 1.5,
      "symbol": "F"
    }, {
      "atomicNumber": 10,
      "boilingpoint": 27.1,
      "discoverers": ["W. Ramsay", "M.W. Travers"],
      "discoveryCountry": "uk",
      "discoveryDate": "1898",
      "electronAffinity": 0.0,
      "electronicConfiguration": "He 2s2 2p6",
      "elementColor": [0.7, 0.89, 0.96],
      "exactMass": 19.99244018,
      "family": "Noblegas",
      "group": 8,
      "ionization": 21.5645,
      "mass": 20.1797,
      "meltingpoint": 24.55,
      "name": "Neon",
      "nameOrigin": "Greek 'neo'. meaning 'new'",
      "period": 2,
      "periodTableBlock": "p",
      "radiusCovalent": 0.69,
      "radiusVDW": 1.54,
      "symbol": "Ne"
    }, {
      "atomicNumber": 11,
      "boilingpoint": 1156.0,
      "discoverers": "Sir Humphrey Davy",
      "discoveryCountry": "uk",
      "discoveryDate": "1807",
      "electronAffinity": 0.547926,
      "electronegativityPauling": 0.93,
      "electronicConfiguration": "Ne 3s1",
      "elementColor": [0.67, 0.36, 0.95],
      "exactMass": 22.98976928,
      "family": "Alkali_Earth",
      "group": 1,
      "ionization": 5.1391,
      "mass": 22.98976928,
      "meltingpoint": 371.0,
      "name": "Sodium",
      "nameOrigin": "Arabic 'natrun' for 'soda'",
      "period": 3,
      "periodTableBlock": "s",
      "radiusCovalent": 1.54,
      "radiusVDW": 2.4,
      "symbol": "Na"
    }, {
      "atomicNumber": 12,
      "boilingpoint": 1380.0,
      "discoverers": "H. B. Davy",
      "discoveryCountry": "uk",
      "discoveryDate": "1808",
      "electronAffinity": 0.0,
      "electronegativityPauling": 1.31,
      "electronicConfiguration": "Ne 3s2",
      "elementColor": [0.54, 1.0, 0.0],
      "exactMass": 23.9850417,
      "family": "Alkaline_Earth",
      "group": 2,
      "ionization": 7.6462,
      "mass": 24.305,
      "meltingpoint": 922.0,
      "name": "Magnesium",
      "nameOrigin": "Named after the city of Magnesia",
      "period": 3,
      "periodTableBlock": "s",
      "radiusCovalent": 1.3,
      "radiusVDW": 2.2,
      "symbol": "Mg"
    }, {
      "atomicNumber": 13,
      "boilingpoint": 2740.0,
      "discoverers": "H. Ch. Oersted",
      "discoveryCountry": "dk",
      "discoveryDate": "1825",
      "electronAffinity": 0.43283,
      "electronegativityPauling": 1.61,
      "electronicConfiguration": "Ne 3s2 3p1",
      "elementColor": [0.75, 0.65, 0.65],
      "exactMass": 26.98153863,
      "family": "Other_Metal",
      "group": 3,
      "ionization": 5.9858,
      "mass": 26.9815386,
      "meltingpoint": 933.5,
      "name": "Aluminium",
      "nameOrigin": "Latin 'alumen'",
      "period": 3,
      "periodTableBlock": "p",
      "radiusCovalent": 1.18,
      "radiusVDW": 2.1,
      "symbol": "Al"
    }, {
      "atomicNumber": 14,
      "boilingpoint": 2630.0,
      "discoverers": "J. J. Berzelius",
      "discoveryCountry": "se",
      "discoveryDate": "1823",
      "electronAffinity": 1.389521,
      "electronegativityPauling": 1.9,
      "electronicConfiguration": "Ne 3s2 3p2",
      "elementColor": [0.5, 0.6, 0.6],
      "exactMass": 27.97692653,
      "family": "Metalloids",
      "group": 4,
      "ionization": 8.1517,
      "mass": 28.0855,
      "meltingpoint": 1683.0,
      "name": "Silicon",
      "nameOrigin": "Latin 'silex'",
      "period": 3,
      "periodTableBlock": "p",
      "radiusCovalent": 1.11,
      "radiusVDW": 2.1,
      "symbol": "Si"
    }, {
      "atomicNumber": 15,
      "boilingpoint": 553.0,
      "discoverers": "H. Brandt",
      "discoveryCountry": "de",
      "discoveryDate": "1669",
      "electronAffinity": 0.7465,
      "electronegativityPauling": 2.19,
      "electronicConfiguration": "Ne 3s2 3p3",
      "elementColor": [1.0, 0.5, 0.0],
      "exactMass": 30.97376163,
      "family": "Non-Metal",
      "group": 5,
      "ionization": 10.4867,
      "mass": 30.973762,
      "meltingpoint": 317.3,
      "name": "Phosphorus",
      "nameOrigin": "Greek 'phosphoros' for 'carries light'",
      "period": 3,
      "periodTableBlock": "p",
      "radiusCovalent": 1.06,
      "radiusVDW": 1.95,
      "symbol": "P"
    }, {
      "atomicNumber": 16,
      "boilingpoint": 717.82,
      "discoveryCountry": "ancient",
      "discoveryDate": "0",
      "electronAffinity": 2.0771029,
      "electronegativityPauling": 2.58,
      "electronicConfiguration": "Ne 3s2 3p4",
      "elementColor": [1.0, 1.0, 0.19],
      "exactMass": 31.972071,
      "family": "Non-Metal",
      "group": 6,
      "ionization": 10.36,
      "mass": 32.065,
      "meltingpoint": 392.2,
      "name": "Sulfur",
      "nameOrigin": "In sanskrit 'sweb' means 'to sleep'",
      "period": 3,
      "periodTableBlock": "p",
      "radiusCovalent": 1.02,
      "radiusVDW": 1.8,
      "symbol": "S"
    }, {
      "atomicNumber": 17,
      "boilingpoint": 239.18,
      "discoverers": "C. W. Scheele",
      "discoveryCountry": "se",
      "discoveryDate": "1774",
      "electronAffinity": 3.612724,
      "electronegativityPauling": 3.16,
      "electronicConfiguration": "Ne 3s2 3p5",
      "elementColor": [0.12, 0.94, 0.12],
      "exactMass": 34.96885268,
      "family": "Halogen",
      "group": 7,
      "ionization": 12.9676,
      "mass": 35.453,
      "meltingpoint": 172.17,
      "name": "Chlorine",
      "nameOrigin": "Greek 'chloros' for 'yellow-green'",
      "period": 3,
      "periodTableBlock": "p",
      "radiusCovalent": 0.99,
      "radiusVDW": 1.8,
      "symbol": "Cl"
    }, {
      "atomicNumber": 18,
      "boilingpoint": 87.45,
      "discoverers": ["W. Ramsay", "J. Rayleigh"],
      "discoveryCountry": "uk",
      "discoveryDate": "1894",
      "electronAffinity": 0.0,
      "electronicConfiguration": "Ne 3s2 3p6",
      "elementColor": [0.5, 0.82, 0.89],
      "exactMass": 39.96238312,
      "family": "Noblegas",
      "group": 8,
      "ionization": 15.7596,
      "mass": 39.948,
      "meltingpoint": 83.95,
      "name": "Argon",
      "nameOrigin": "Greek 'aergon' for 'inactive'",
      "period": 3,
      "periodTableBlock": "p",
      "radiusCovalent": 0.97,
      "radiusVDW": 1.88,
      "symbol": "Ar"
    }, {
      "atomicNumber": 19,
      "boilingpoint": 1033.0,
      "discoverers": "H. B. Davy",
      "discoveryCountry": "uk",
      "discoveryDate": "1807",
      "electronAffinity": 0.501459,
      "electronegativityPauling": 0.82,
      "electronicConfiguration": "Ar 4s1",
      "elementColor": [0.56, 0.25, 0.83],
      "exactMass": 38.96370668,
      "family": "Alkali_Earth",
      "group": 1,
      "ionization": 4.3407,
      "mass": 39.0983,
      "meltingpoint": 336.8,
      "name": "Potassium",
      "nameOrigin": "Arabic 'al qaliy' for potash",
      "period": 4,
      "periodTableBlock": "s",
      "radiusCovalent": 1.96,
      "radiusVDW": 2.8,
      "symbol": "K"
    }, {
      "atomicNumber": 20,
      "boilingpoint": 1757.0,
      "discoverers": "H. B. Davy",
      "discoveryCountry": "uk",
      "discoveryDate": "1808",
      "electronAffinity": 0.02455,
      "electronegativityPauling": 1.0,
      "electronicConfiguration": "Ar 4s2",
      "elementColor": [0.24, 1.0, 0.0],
      "exactMass": 39.96259098,
      "family": "Alkaline_Earth",
      "group": 2,
      "ionization": 6.1132,
      "mass": 40.078,
      "meltingpoint": 1112.0,
      "name": "Calcium",
      "nameOrigin": "Latin 'calx' for 'lime'",
      "period": 4,
      "periodTableBlock": "s",
      "radiusCovalent": 1.74,
      "radiusVDW": 2.4,
      "symbol": "Ca"
    }, {
      "atomicNumber": 21,
      "boilingpoint": 3109.0,
      "discoverers": "L. Nilson",
      "discoveryCountry": "se",
      "discoveryDate": "1879",
      "electronAffinity": 0.188,
      "electronegativityPauling": 1.36,
      "electronicConfiguration": "Ar 3d1 4s2",
      "elementColor": [0.9, 0.9, 0.9],
      "exactMass": 44.9559119,
      "family": "Transition",
      "group": 3,
      "ionization": 6.5615,
      "mass": 44.955912,
      "meltingpoint": 1814.0,
      "name": "Scandium",
      "nameOrigin": "Named because it was found in Scandinavia",
      "period": 4,
      "periodTableBlock": "d",
      "radiusCovalent": 1.44,
      "radiusVDW": 2.3,
      "symbol": "Sc"
    }, {
      "atomicNumber": 22,
      "boilingpoint": 3560.0,
      "discoverers": "W. Gregor",
      "discoveryCountry": "uk",
      "discoveryDate": "1791",
      "electronAffinity": 0.084,
      "electronegativityPauling": 1.54,
      "electronicConfiguration": "Ar 3d2 4s2",
      "elementColor": [0.75, 0.76, 0.78],
      "exactMass": 47.9479463,
      "family": "Transition",
      "group": 4,
      "ionization": 6.8281,
      "mass": 47.867,
      "meltingpoint": 1935.0,
      "name": "Titanium",
      "nameOrigin": "The Titans were giants in Greek mythology",
      "period": 4,
      "periodTableBlock": "d",
      "radiusCovalent": 1.36,
      "radiusVDW": 2.15,
      "symbol": "Ti"
    }, {
      "atomicNumber": 23,
      "boilingpoint": 3650.0,
      "discoverers": "N. Sefstr\u00f6m",
      "discoveryCountry": "se",
      "discoveryDate": "1830",
      "electronAffinity": 0.525,
      "electronegativityPauling": 1.63,
      "electronicConfiguration": "Ar 3d3 4s2",
      "elementColor": [0.65, 0.65, 0.67],
      "exactMass": 50.9439595,
      "family": "Transition",
      "group": 5,
      "ionization": 6.7462,
      "mass": 50.9415,
      "meltingpoint": 2163.0,
      "name": "Vanadium",
      "nameOrigin": "'Vanadis' is another name for the Nordic goddess Freyja",
      "period": 4,
      "periodTableBlock": "d",
      "radiusCovalent": 1.25,
      "radiusVDW": 2.05,
      "symbol": "V"
    }, {
      "atomicNumber": 24,
      "boilingpoint": 2945.0,
      "discoverers": "Nicholas Louis Vauquelin",
      "discoveryCountry": "fr",
      "discoveryDate": "1797",
      "electronAffinity": 0.67584,
      "electronegativityPauling": 1.66,
      "electronicConfiguration": "Ar 3d5 4s1",
      "elementColor": [0.54, 0.6, 0.78],
      "exactMass": 51.9405075,
      "family": "Transition",
      "group": 6,
      "ionization": 6.7665,
      "mass": 51.9961,
      "meltingpoint": 2130.0,
      "name": "Chromium",
      "nameOrigin": "Greek 'chroma' means 'color'",
      "period": 4,
      "periodTableBlock": "d",
      "radiusCovalent": 1.27,
      "radiusVDW": 2.05,
      "symbol": "Cr"
    }, {
      "atomicNumber": 25,
      "boilingpoint": 2235.0,
      "discoverers": "C. W. Scheele",
      "discoveryCountry": "se",
      "discoveryDate": "1774",
      "electronAffinity": 0.0,
      "electronegativityPauling": 1.55,
      "electronicConfiguration": "Ar 3d5 4s2",
      "elementColor": [0.61, 0.48, 0.78],
      "exactMass": 54.9380451,
      "family": "Transition",
      "group": 7,
      "ionization": 7.434,
      "mass": 54.938045,
      "meltingpoint": 1518.0,
      "name": "Manganese",
      "nameOrigin": "It was discovered near a town named Magnesia in black earth. Thus, it was named 'magnesia nigra', or for short, Manganese.",
      "period": 4,
      "periodTableBlock": "d",
      "radiusCovalent": 1.39,
      "radiusVDW": 2.05,
      "symbol": "Mn"
    }, {
      "atomicNumber": 26,
      "boilingpoint": 3023.0,
      "discoveryCountry": "ancient",
      "discoveryDate": "0",
      "electronAffinity": 0.151,
      "electronegativityPauling": 1.83,
      "electronicConfiguration": "Ar 3d6 4s2",
      "elementColor": [0.5, 0.48, 0.78],
      "exactMass": 55.9349375,
      "family": "Transition",
      "group": 8,
      "ionization": 7.9024,
      "mass": 55.845,
      "meltingpoint": 1808.0,
      "name": "Iron",
      "nameOrigin": "Latin 'ferrum'",
      "period": 4,
      "periodTableBlock": "d",
      "radiusCovalent": 1.25,
      "radiusVDW": 2.05,
      "symbol": "Fe"
    }, {
      "atomicNumber": 27,
      "boilingpoint": 3143.0,
      "discoverers": "G. Brandt",
      "discoveryCountry": "se",
      "discoveryDate": "1737",
      "electronAffinity": 0.6633,
      "electronegativityPauling": 1.88,
      "electronicConfiguration": "Ar 3d7 4s2",
      "elementColor": [0.44, 0.48, 0.78],
      "exactMass": 58.933195,
      "family": "Transition",
      "group": 8,
      "ionization": 7.881,
      "mass": 58.933195,
      "meltingpoint": 1768.0,
      "name": "Cobalt",
      "nameOrigin": "Named after the German word 'Kobold' for 'goblin'",
      "period": 4,
      "periodTableBlock": "d",
      "radiusCovalent": 1.26,
      "radiusVDW": 2.0,
      "symbol": "Co"
    }, {
      "atomicNumber": 28,
      "boilingpoint": 3005.0,
      "discoverers": "A. F. Cronstedt",
      "discoveryCountry": "se",
      "discoveryDate": "1751",
      "electronAffinity": 1.15716,
      "electronegativityPauling": 1.91,
      "electronicConfiguration": "Ar 3d8 4s2",
      "elementColor": [0.36, 0.48, 0.76],
      "exactMass": 57.9353429,
      "family": "Transition",
      "group": 8,
      "ionization": 7.6398,
      "mass": 58.6934,
      "meltingpoint": 1726.0,
      "name": "Nickel",
      "nameOrigin": "'Nickel' was the name of a mountain goblin",
      "period": 4,
      "periodTableBlock": "d",
      "radiusCovalent": 1.21,
      "radiusVDW": 2.0,
      "symbol": "Ni"
    }, {
      "atomicNumber": 29,
      "boilingpoint": 2840.0,
      "discoveryCountry": "ancient",
      "discoveryDate": "0",
      "electronAffinity": 1.23578,
      "electronegativityPauling": 1.9,
      "electronicConfiguration": "Ar 3d10 4s1",
      "elementColor": [1.0, 0.48, 0.38],
      "exactMass": 62.9295975,
      "family": "Transition",
      "group": 1,
      "ionization": 7.7264,
      "mass": 63.546,
      "meltingpoint": 1356.6,
      "name": "Copper",
      "nameOrigin": "Greek 'cuprum' for Cypres",
      "period": 4,
      "periodTableBlock": "d",
      "radiusCovalent": 1.38,
      "radiusVDW": 2.0,
      "symbol": "Cu"
    }, {
      "atomicNumber": 30,
      "boilingpoint": 1180.0,
      "discoverers": "Andreas Marggraf",
      "discoveryCountry": "de",
      "discoveryDate": "1746",
      "electronAffinity": 0.0,
      "electronegativityPauling": 1.65,
      "electronicConfiguration": "Ar 3d10 4s2",
      "elementColor": [0.49, 0.5, 0.69],
      "exactMass": 63.9291422,
      "family": "Transition",
      "group": 2,
      "ionization": 9.3942,
      "mass": 65.38,
      "meltingpoint": 692.73,
      "name": "Zinc",
      "nameOrigin": "German 'zinking' for 'rough', because zinc ore is very rough",
      "period": 4,
      "periodTableBlock": "d",
      "radiusCovalent": 1.31,
      "radiusVDW": 2.1,
      "symbol": "Zn"
    }, {
      "atomicNumber": 31,
      "boilingpoint": 2478.0,
      "discoverers": "P. E. Lecoq de Boisbaudran",
      "discoveryCountry": "fr",
      "discoveryDate": "1875",
      "electronAffinity": 0.41,
      "electronegativityPauling": 1.81,
      "electronicConfiguration": "Ar 3d10 4s2 4p1",
      "elementColor": [0.76, 0.56, 0.56],
      "exactMass": 68.9255736,
      "family": "Other_Metal",
      "group": 3,
      "ionization": 5.9993,
      "mass": 69.723,
      "meltingpoint": 302.92,
      "name": "Gallium",
      "nameOrigin": "'Gallia' is an old name for France",
      "period": 4,
      "periodTableBlock": "p",
      "radiusCovalent": 1.26,
      "radiusVDW": 2.1,
      "symbol": "Ga"
    }, {
      "atomicNumber": 32,
      "boilingpoint": 3107.0,
      "discoverers": "C. A. Winkler",
      "discoveryCountry": "de",
      "discoveryDate": "1886",
      "electronAffinity": 1.232712,
      "electronegativityPauling": 2.01,
      "electronicConfiguration": "Ar 3d10 4s2 4p2",
      "elementColor": [0.4, 0.56, 0.56],
      "exactMass": 73.9211778,
      "family": "Metalloids",
      "group": 4,
      "ionization": 7.8994,
      "mass": 72.64,
      "meltingpoint": 1211.5,
      "name": "Germanium",
      "nameOrigin": "Latin 'germania' is an old name for Germany",
      "period": 4,
      "periodTableBlock": "p",
      "radiusCovalent": 1.22,
      "radiusVDW": 2.1,
      "symbol": "Ge"
    }, {
      "atomicNumber": 33,
      "boilingpoint": 876.0,
      "discoveryCountry": "ancient",
      "discoveryDate": "0",
      "electronAffinity": 0.814,
      "electronegativityPauling": 2.18,
      "electronicConfiguration": "Ar 3d10 4s2 4p3",
      "elementColor": [0.74, 0.5, 0.89],
      "exactMass": 74.9215965,
      "family": "Metalloids",
      "group": 5,
      "ionization": 9.7886,
      "mass": 74.9216,
      "meltingpoint": 1090.0,
      "name": "Arsenic",
      "nameOrigin": "Greek 'arsenikos' for 'male' or 'bold'",
      "period": 4,
      "periodTableBlock": "p",
      "radiusCovalent": 1.19,
      "radiusVDW": 2.05,
      "symbol": "As"
    }, {
      "atomicNumber": 34,
      "boilingpoint": 958.0,
      "discoverers": "J. J. Berzelius",
      "discoveryCountry": "se",
      "discoveryDate": "1817",
      "electronAffinity": 2.02067,
      "electronegativityPauling": 2.55,
      "electronicConfiguration": "Ar 3d10 4s2 4p4",
      "elementColor": [1.0, 0.63, 0.0],
      "exactMass": 79.9165213,
      "family": "Non-Metal",
      "group": 6,
      "ionization": 9.7524,
      "mass": 78.96,
      "meltingpoint": 494.0,
      "name": "Selenium",
      "nameOrigin": "Greek 'selena' for 'moon'",
      "period": 4,
      "periodTableBlock": "p",
      "radiusCovalent": 1.16,
      "radiusVDW": 1.9,
      "symbol": "Se"
    }, {
      "atomicNumber": 35,
      "boilingpoint": 331.85,
      "discoverers": "A. J. Balard",
      "discoveryCountry": "fr",
      "discoveryDate": "1826",
      "electronAffinity": 3.363588,
      "electronegativityPauling": 2.96,
      "electronicConfiguration": "Ar 3d10 4s2 4p5",
      "elementColor": [0.65, 0.16, 0.16],
      "exactMass": 78.9183371,
      "family": "Halogen",
      "group": 7,
      "ionization": 11.8138,
      "mass": 79.904,
      "meltingpoint": 265.95,
      "name": "Bromine",
      "nameOrigin": "Greek 'bromos' for 'smells badly'",
      "period": 4,
      "periodTableBlock": "p",
      "radiusCovalent": 1.14,
      "radiusVDW": 1.9,
      "symbol": "Br"
    }, {
      "atomicNumber": 36,
      "boilingpoint": 120.85,
      "discoverers": ["W. Ramsay", "M. W. Travers"],
      "discoveryCountry": "uk",
      "discoveryDate": "1898",
      "electronAffinity": 0.0,
      "electronegativityPauling": 3.0,
      "electronicConfiguration": "Ar 3d10 4s2 4p6",
      "elementColor": [0.36, 0.72, 0.82],
      "exactMass": 83.911507,
      "family": "Noblegas",
      "group": 8,
      "ionization": 13.9996,
      "mass": 83.798,
      "meltingpoint": 116.0,
      "name": "Krypton",
      "nameOrigin": "Greek 'kryptos' for 'hidden'",
      "period": 4,
      "periodTableBlock": "p",
      "radiusCovalent": 1.1,
      "radiusVDW": 2.02,
      "symbol": "Kr"
    }, {
      "atomicNumber": 37,
      "boilingpoint": 961.0,
      "discoverers": ["Robert W. Bunsen", "Gustav R. Kirchhoff"],
      "discoveryCountry": "de",
      "discoveryDate": "1861",
      "electronAffinity": 0.485916,
      "electronegativityPauling": 0.82,
      "electronicConfiguration": "Kr 5s1",
      "elementColor": [0.44, 0.18, 0.69],
      "exactMass": 84.91178974,
      "family": "Alkali_Earth",
      "group": 1,
      "ionization": 4.1771,
      "mass": 85.4678,
      "meltingpoint": 312.63,
      "name": "Rubidium",
      "nameOrigin": "Latin 'rubidus' for 'dark red'",
      "period": 5,
      "periodTableBlock": "s",
      "radiusCovalent": 2.11,
      "radiusVDW": 2.9,
      "symbol": "Rb"
    }, {
      "atomicNumber": 38,
      "boilingpoint": 1655.0,
      "discoverers": "H. B. Davy",
      "discoveryCountry": "uk",
      "discoveryDate": "1790",
      "electronAffinity": 0.05206,
      "electronegativityPauling": 0.95,
      "electronicConfiguration": "Kr 5s2",
      "elementColor": [0.0, 1.0, 0.0],
      "exactMass": 87.9056121,
      "family": "Alkaline_Earth",
      "group": 2,
      "ionization": 5.6949,
      "mass": 87.62,
      "meltingpoint": 1042.0,
      "name": "Strontium",
      "nameOrigin": "Named after the mineral Strontianit",
      "period": 5,
      "periodTableBlock": "s",
      "radiusCovalent": 1.92,
      "radiusVDW": 2.55,
      "symbol": "Sr"
    }, {
      "atomicNumber": 39,
      "boilingpoint": 3611.0,
      "discoverers": "Johann Gadolin",
      "discoveryCountry": "fi",
      "discoveryDate": "1794",
      "electronAffinity": 0.307,
      "electronegativityPauling": 1.22,
      "electronicConfiguration": "Kr 4d1 5s2",
      "elementColor": [0.58, 1.0, 1.0],
      "exactMass": 88.9058483,
      "family": "Transition",
      "group": 3,
      "ionization": 6.2173,
      "mass": 88.90585,
      "meltingpoint": 1795.0,
      "name": "Yttrium",
      "nameOrigin": "Named after the small town of Ytterby near Stockholm in Sweden. Terbium. Ytterbium and Gadolinium are also named after this town.",
      "period": 5,
      "periodTableBlock": "d",
      "radiusCovalent": 1.62,
      "radiusVDW": 2.4,
      "symbol": "Y"
    }, {
      "atomicNumber": 40,
      "boilingpoint": 4682.0,
      "discoverers": "Martin Heinrich Klaproth",
      "discoveryCountry": "de",
      "discoveryDate": "1789",
      "electronAffinity": 0.426,
      "electronegativityPauling": 1.33,
      "electronicConfiguration": "Kr 4d2 5s2",
      "elementColor": [0.58, 0.88, 0.88],
      "exactMass": 89.9047044,
      "family": "Transition",
      "group": 4,
      "ionization": 6.6339,
      "mass": 91.224,
      "meltingpoint": 2128.0,
      "name": "Zirconium",
      "nameOrigin": "Named after the mineral zircon",
      "period": 5,
      "periodTableBlock": "d",
      "radiusCovalent": 1.48,
      "radiusVDW": 2.3,
      "symbol": "Zr"
    }, {
      "atomicNumber": 41,
      "boilingpoint": 5015.0,
      "discoverers": "Ch. Hatchett",
      "discoveryCountry": "uk",
      "discoveryDate": "1801",
      "electronAffinity": 0.893,
      "electronegativityPauling": 1.6,
      "electronicConfiguration": "Kr 4d4",
      "elementColor": [0.45, 0.76, 0.79],
      "exactMass": 92.9063781,
      "family": "Transition",
      "group": 5,
      "ionization": 6.7589,
      "mass": 92.90638,
      "meltingpoint": 2742.0,
      "name": "Niobium",
      "nameOrigin": "Named after Niobe, the daughter of the Greek god Tantalus.",
      "period": 5,
      "periodTableBlock": "d",
      "radiusCovalent": 1.37,
      "radiusVDW": 2.15,
      "symbol": "Nb"
    }, {
      "atomicNumber": 42,
      "boilingpoint": 4912.0,
      "discoverers": "C. W. Scheele",
      "discoveryCountry": "se",
      "discoveryDate": "1778",
      "electronAffinity": 0.7472,
      "electronegativityPauling": 2.16,
      "electronicConfiguration": "Kr 4d5 5s1",
      "elementColor": [0.33, 0.71, 0.71],
      "exactMass": 97.9054082,
      "family": "Transition",
      "group": 6,
      "ionization": 7.0924,
      "mass": 95.96,
      "meltingpoint": 2896.0,
      "name": "Molybdenum",
      "nameOrigin": "This name has Greek roots. It means 'like Platinum' - it was difficult to distinguish Molybdenum from Platinum.",
      "period": 5,
      "periodTableBlock": "d",
      "radiusCovalent": 1.45,
      "radiusVDW": 2.1,
      "symbol": "Mo"
    }, {
      "atomicNumber": 43,
      "boilingpoint": 4538.0,
      "discoverers": ["C. Perrier", "E. G. Segre"],
      "discoveryCountry": "it",
      "discoveryDate": "1937",
      "electronAffinity": 0.55,
      "electronegativityPauling": 1.9,
      "electronicConfiguration": "Kr 4d6 5s1",
      "elementColor": [0.23, 0.62, 0.62],
      "exactMass": 97.907216,
      "family": "Transition",
      "group": 7,
      "ionization": 7.28,
      "mass": 98.0,
      "meltingpoint": 2477.0,
      "name": "Technetium",
      "nameOrigin": "Greek 'technetos' for artificial",
      "period": 5,
      "periodTableBlock": "d",
      "radiusCovalent": 1.56,
      "radiusVDW": 2.05,
      "symbol": "Tc"
    }, {
      "atomicNumber": 44,
      "boilingpoint": 4425.0,
      "discoverers": "K. Klaus",
      "discoveryCountry": "ru",
      "discoveryDate": "1844",
      "electronAffinity": 1.04638,
      "electronegativityPauling": 2.2,
      "electronicConfiguration": "Kr 4d7 5s1",
      "elementColor": [0.14, 0.56, 0.56],
      "exactMass": 101.9043493,
      "family": "Transition",
      "group": 8,
      "ionization": 7.3605,
      "mass": 101.07,
      "meltingpoint": 2610.0,
      "name": "Ruthenium",
      "nameOrigin": "Ruthenia is the old name of Russia",
      "period": 5,
      "periodTableBlock": "d",
      "radiusCovalent": 1.26,
      "radiusVDW": 2.05,
      "symbol": "Ru"
    }, {
      "atomicNumber": 45,
      "boilingpoint": 3970.0,
      "discoverers": "W. Wollaston",
      "discoveryCountry": "uk",
      "discoveryDate": "1803",
      "electronAffinity": 1.14289,
      "electronegativityPauling": 2.28,
      "electronicConfiguration": "Kr 4d8 5s1",
      "elementColor": [0.04, 0.49, 0.55],
      "exactMass": 102.905504,
      "family": "Transition",
      "group": 8,
      "ionization": 7.4589,
      "mass": 102.9055,
      "meltingpoint": 2236.0,
      "name": "Rhodium",
      "nameOrigin": "Greek 'rhodeos' means 'red like a rose'",
      "period": 5,
      "periodTableBlock": "d",
      "radiusCovalent": 1.35,
      "radiusVDW": 2.0,
      "symbol": "Rh"
    }, {
      "atomicNumber": 46,
      "boilingpoint": 3240.0,
      "discoveryCountry": "uk",
      "discoveryDate": "1803",
      "electronAffinity": 0.56214,
      "electronegativityPauling": 2.2,
      "electronicConfiguration": "Kr 4d10",
      "elementColor": [0.0, 0.41, 0.52],
      "exactMass": 105.903486,
      "family": "Transition",
      "group": 8,
      "ionization": 8.3369,
      "mass": 106.42,
      "meltingpoint": 1825.0,
      "name": "Palladium",
      "nameOrigin": "Named after the asteroid Pallas",
      "period": 5,
      "periodTableBlock": "d",
      "radiusCovalent": 1.31,
      "radiusVDW": 2.05,
      "symbol": "Pd"
    }, {
      "atomicNumber": 47,
      "boilingpoint": 2436.0,
      "discoveryCountry": "ancient",
      "discoveryDate": "0",
      "electronAffinity": 1.30447,
      "electronegativityPauling": 1.93,
      "electronicConfiguration": "Kr 4d10 5s1",
      "elementColor": [0.88, 0.88, 1.0],
      "exactMass": 106.905097,
      "family": "Transition",
      "group": 1,
      "ionization": 7.5762,
      "mass": 107.8682,
      "meltingpoint": 1235.1,
      "name": "Silver",
      "nameOrigin": "Latin 'argentum' for silver",
      "period": 5,
      "periodTableBlock": "d",
      "radiusCovalent": 1.53,
      "radiusVDW": 2.1,
      "symbol": "Ag"
    }, {
      "atomicNumber": 48,
      "boilingpoint": 1040.0,
      "discoverers": "F. Stromeyer",
      "discoveryCountry": "de",
      "discoveryDate": "1817",
      "electronAffinity": 0.0,
      "electronegativityPauling": 1.69,
      "electronicConfiguration": "Kr 4d10 5s2",
      "elementColor": [1.0, 0.85, 0.56],
      "exactMass": 113.9033585,
      "family": "Transition",
      "group": 2,
      "ionization": 8.9938,
      "mass": 112.411,
      "meltingpoint": 594.26,
      "name": "Cadmium",
      "nameOrigin": "Greek 'kadmia' ('Galmei' = Zinc carbonate)",
      "period": 5,
      "periodTableBlock": "d",
      "radiusCovalent": 1.48,
      "radiusVDW": 2.2,
      "symbol": "Cd"
    }, {
      "atomicNumber": 49,
      "boilingpoint": 2350.0,
      "discoverers": ["F. Reich", "H.T. Richter"],
      "discoveryCountry": "de",
      "discoveryDate": "1863",
      "electronAffinity": 0.404,
      "electronegativityPauling": 1.78,
      "electronicConfiguration": "Kr 4d10 5s2 5p1",
      "elementColor": [0.65, 0.46, 0.45],
      "exactMass": 114.903878,
      "family": "Other_Metal",
      "group": 3,
      "ionization": 5.7864,
      "mass": 114.818,
      "meltingpoint": 429.78,
      "name": "Indium",
      "nameOrigin": "Named after 'Indigo' because of its blue spectrum",
      "period": 5,
      "periodTableBlock": "p",
      "radiusCovalent": 1.44,
      "radiusVDW": 2.2,
      "symbol": "In"
    }, {
      "atomicNumber": 50,
      "boilingpoint": 2876.0,
      "discoveryCountry": "ancient",
      "discoveryDate": "0",
      "electronAffinity": 1.112066,
      "electronegativityPauling": 1.96,
      "electronicConfiguration": "Kr 4d10 5s2 5p2",
      "elementColor": [0.4, 0.5, 0.5],
      "exactMass": 119.9021947,
      "family": "Other_Metal",
      "group": 4,
      "ionization": 7.3439,
      "mass": 118.71,
      "meltingpoint": 505.12,
      "name": "Tin",
      "nameOrigin": "Latin 'stannum' for tin",
      "period": 5,
      "periodTableBlock": "p",
      "radiusCovalent": 1.41,
      "radiusVDW": 2.25,
      "symbol": "Sn"
    }, {
      "atomicNumber": 51,
      "boilingpoint": 1860.0,
      "discoveryCountry": "ancient",
      "discoveryDate": "0",
      "electronAffinity": 1.047401,
      "electronegativityPauling": 2.05,
      "electronicConfiguration": "Kr 4d10 5s2 5p3",
      "elementColor": [0.62, 0.39, 0.71],
      "exactMass": 120.9038157,
      "family": "Metalloids",
      "group": 5,
      "ionization": 8.6084,
      "mass": 121.76,
      "meltingpoint": 903.91,
      "name": "Antimony",
      "nameOrigin": "Arabic 'anthos ammonos' for 'blossom of the god Ammon'",
      "period": 5,
      "periodTableBlock": "p",
      "radiusCovalent": 1.38,
      "radiusVDW": 2.2,
      "symbol": "Sb"
    }, {
      "atomicNumber": 52,
      "boilingpoint": 1261.0,
      "discoverers": "Franz Joseph Muller von Reichstein",
      "discoveryCountry": "de",
      "discoveryDate": "1782",
      "electronAffinity": 1.970875,
      "electronegativityPauling": 2.1,
      "electronicConfiguration": "Kr 4d10 5s2 5p4",
      "elementColor": [0.83, 0.48, 0.0],
      "exactMass": 129.9062244,
      "family": "Metalloids",
      "group": 6,
      "ionization": 9.0096,
      "mass": 127.6,
      "meltingpoint": 722.72,
      "name": "Tellurium",
      "nameOrigin": "Latin 'tellus' or 'telluris' for 'Planet Earth'",
      "period": 5,
      "periodTableBlock": "p",
      "radiusCovalent": 1.35,
      "radiusVDW": 2.1,
      "symbol": "Te"
    }, {
      "atomicNumber": 53,
      "boilingpoint": 457.5,
      "discoverers": "Bernard Courtois",
      "discoveryCountry": "fr",
      "discoveryDate": "1811",
      "electronAffinity": 3.059038,
      "electronegativityPauling": 2.66,
      "electronicConfiguration": "Kr 4d10 5s2 5p5",
      "elementColor": [0.58, 0.0, 0.58],
      "exactMass": 126.904473,
      "family": "Halogen",
      "group": 7,
      "ionization": 10.4513,
      "mass": 126.90447,
      "meltingpoint": 386.7,
      "name": "Iodine",
      "nameOrigin": "Greek 'ioeides' for 'violet'.",
      "period": 5,
      "periodTableBlock": "p",
      "radiusCovalent": 1.33,
      "radiusVDW": 2.1,
      "symbol": "I"
    }, {
      "atomicNumber": 54,
      "boilingpoint": 165.1,
      "discoverers": ["W. Ramsay", "M. W. Travers"],
      "discoveryCountry": "uk",
      "discoveryDate": "1898",
      "electronAffinity": 0.0,
      "electronegativityPauling": 2.6,
      "electronicConfiguration": "Kr 4d10 5s2 5p6",
      "elementColor": [0.26, 0.62, 0.69],
      "exactMass": 131.9041535,
      "family": "Noblegas",
      "group": 8,
      "ionization": 12.1298,
      "mass": 131.293,
      "meltingpoint": 161.39,
      "name": "Xenon",
      "nameOrigin": "Greek 'xenos' for 'foreigner'",
      "period": 5,
      "periodTableBlock": "p",
      "radiusCovalent": 1.3,
      "radiusVDW": 2.16,
      "symbol": "Xe"
    }, {
      "atomicNumber": 55,
      "boilingpoint": 944.0,
      "discoverers": ["Robert Wilhelm Bunsen", "Gustav Robert Kirchhoff"],
      "discoveryCountry": "de",
      "discoveryDate": "1860",
      "electronAffinity": 0.471626,
      "electronegativityPauling": 0.79,
      "electronicConfiguration": "Xe 6s1",
      "elementColor": [0.34, 0.09, 0.56],
      "exactMass": 132.9054519,
      "family": "Alkali_Earth",
      "group": 1,
      "ionization": 3.8939,
      "mass": 132.9054519,
      "meltingpoint": 301.54,
      "name": "Caesium",
      "nameOrigin": "Latin 'caesius' for 'heaven blue'.",
      "period": 6,
      "periodTableBlock": "s",
      "radiusCovalent": 2.25,
      "radiusVDW": 3.0,
      "symbol": "Cs"
    }, {
      "atomicNumber": 56,
      "boilingpoint": 2078.0,
      "discoverers": "Humphry Bartholomew Davy",
      "discoveryCountry": "uk",
      "discoveryDate": "1808",
      "electronAffinity": 0.14462,
      "electronegativityPauling": 0.89,
      "electronicConfiguration": "Xe 6s2",
      "elementColor": [0.0, 0.79, 0.0],
      "exactMass": 137.9052472,
      "family": "Alkaline_Earth",
      "group": 2,
      "ionization": 5.2117,
      "mass": 137.327,
      "meltingpoint": 1002.0,
      "name": "Barium",
      "nameOrigin": "Greek 'barys' for 'heavy'",
      "period": 6,
      "periodTableBlock": "s",
      "radiusCovalent": 1.98,
      "radiusVDW": 2.7,
      "symbol": "Ba"
    }, {
      "atomicNumber": 57,
      "boilingpoint": 3737.0,
      "discoverers": "K. G. Mosander",
      "discoveryCountry": "se",
      "discoveryDate": "1839",
      "electronAffinity": 0.47,
      "electronegativityPauling": 1.1,
      "electronicConfiguration": "Xe 5d1 6s2",
      "elementColor": [0.44, 0.83, 1.0],
      "exactMass": 138.9063533,
      "family": "Rare_Earth",
      "group": 3,
      "ionization": 5.5769,
      "mass": 138.90547,
      "meltingpoint": 1191.0,
      "name": "Lanthanum",
      "nameOrigin": "Greek 'lanthanein' for 'hidden'. The Lanthanoids are also called the 'rare earth' elements.",
      "period": 6,
      "periodTableBlock": "f",
      "radiusCovalent": 1.69,
      "radiusVDW": 2.5,
      "symbol": "La"
    }, {
      "atomicNumber": 58,
      "boilingpoint": 3715.0,
      "discoverers": ["J\u00f6ns Jacob Berzelius", "W. Hisinger", "M. Klaproth"],
      "discoveryDate": "1803",
      "electronAffinity": 0.5,
      "electronegativityPauling": 1.12,
      "electronicConfiguration": "Xe 4f1 5d1 6s2",
      "elementColor": [1.0, 1.0, 0.78],
      "exactMass": 139.9054387,
      "family": "Rare_Earth",
      "group": 4,
      "ionization": 5.5387,
      "mass": 140.116,
      "meltingpoint": 1071.0,
      "name": "Cerium",
      "nameOrigin": "Named after the planetoid Ceres",
      "period": 6,
      "periodTableBlock": "f",
      "radiusVDW": 2.48,
      "symbol": "Ce"
    }, {
      "atomicNumber": 59,
      "boilingpoint": 3785.0,
      "discoverers": "Carl F. Auer von Welsbach",
      "discoveryDate": "1885",
      "electronAffinity": 0.5,
      "electronegativityPauling": 1.13,
      "electronicConfiguration": "Xe 4f3 6s2",
      "elementColor": [0.85, 1.0, 0.78],
      "exactMass": 140.9076528,
      "family": "Rare_Earth",
      "group": 5,
      "ionization": 5.473,
      "mass": 140.90765,
      "meltingpoint": 1204.0,
      "name": "Praseodymium",
      "nameOrigin": "Greek 'prasinos didymos' for 'green twin'",
      "period": 6,
      "periodTableBlock": "f",
      "radiusVDW": 2.47,
      "symbol": "Pr"
    }, {
      "atomicNumber": 60,
      "boilingpoint": 3347.0,
      "discoverers": "Carl F. Auer von Welsbach",
      "discoveryDate": "1885",
      "electronAffinity": 0.5,
      "electronegativityPauling": 1.14,
      "electronicConfiguration": "Xe 4f4 6s2",
      "elementColor": [0.78, 1.0, 0.78],
      "exactMass": 141.9077233,
      "family": "Rare_Earth",
      "group": 6,
      "ionization": 5.525,
      "mass": 144.242,
      "meltingpoint": 1294.0,
      "name": "Neodymium",
      "nameOrigin": "Greek 'neos didymos' for 'new twin'",
      "period": 6,
      "periodTableBlock": "f",
      "radiusVDW": 2.45,
      "symbol": "Nd"
    }, {
      "atomicNumber": 61,
      "boilingpoint": 3273.0,
      "discoverers": ["J. A. Marinsky", "C. D. Coryell", "L. E. Glendenin"],
      "discoveryDate": "1945",
      "electronAffinity": 0.5,
      "electronicConfiguration": "Xe 4f5 6s2",
      "elementColor": [0.64, 1.0, 0.78],
      "exactMass": 144.912749,
      "family": "Rare_Earth",
      "group": 7,
      "ionization": 5.582,
      "mass": 145.0,
      "meltingpoint": 1315.0,
      "name": "Promethium",
      "nameOrigin": "Named after the Greek Prometheus. Prometheus stole the fire from the gods and gave it to mankind.",
      "period": 6,
      "periodTableBlock": "f",
      "radiusVDW": 2.43,
      "symbol": "Pm"
    }, {
      "atomicNumber": 62,
      "boilingpoint": 2067.0,
      "discoverers": "P. Lecoq de Boisbaudran",
      "discoveryDate": "1879",
      "electronAffinity": 0.5,
      "electronegativityPauling": 1.17,
      "electronicConfiguration": "Xe 4f6 6s2",
      "elementColor": [0.56, 1.0, 0.78],
      "exactMass": 151.9197324,
      "family": "Rare_Earth",
      "group": 8,
      "ionization": 5.6437,
      "mass": 150.36,
      "meltingpoint": 1347.0,
      "name": "Samarium",
      "nameOrigin": "Named after the mineral Samarskit",
      "period": 6,
      "periodTableBlock": "f",
      "radiusVDW": 2.42,
      "symbol": "Sm"
    }, {
      "atomicNumber": 63,
      "boilingpoint": 1800.0,
      "discoverers": "E. A. Demarcay",
      "discoveryDate": "1901",
      "electronAffinity": 0.5,
      "electronicConfiguration": "Xe 4f7 6s2",
      "elementColor": [0.38, 1.0, 0.78],
      "exactMass": 152.9212303,
      "family": "Rare_Earth",
      "group": 8,
      "ionization": 5.6704,
      "mass": 151.964,
      "meltingpoint": 1095.0,
      "name": "Europium",
      "nameOrigin": "Named after Europe",
      "period": 6,
      "periodTableBlock": "f",
      "radiusVDW": 2.4,
      "symbol": "Eu"
    }, {
      "atomicNumber": 64,
      "boilingpoint": 3545.0,
      "discoverers": "Jean de Marignac",
      "discoveryDate": "1880",
      "electronAffinity": 0.5,
      "electronegativityPauling": 1.2,
      "electronicConfiguration": "Xe 4f7 5d1 6s2",
      "elementColor": [0.27, 1.0, 0.78],
      "exactMass": 157.9241039,
      "family": "Rare_Earth",
      "group": 8,
      "ionization": 6.1498,
      "mass": 157.25,
      "meltingpoint": 1585.0,
      "name": "Gadolinium",
      "nameOrigin": "Named after the Finnish chemist Johan Gadolin",
      "period": 6,
      "periodTableBlock": "f",
      "radiusVDW": 2.38,
      "symbol": "Gd"
    }, {
      "atomicNumber": 65,
      "boilingpoint": 3500.0,
      "discoverers": "K. G. Mosander",
      "discoveryDate": "1843",
      "electronAffinity": 0.5,
      "electronicConfiguration": "Xe 4f9 6s2",
      "elementColor": [0.19, 1.0, 0.78],
      "exactMass": 158.9253468,
      "family": "Rare_Earth",
      "group": 1,
      "ionization": 5.8638,
      "mass": 158.92535,
      "meltingpoint": 1629.0,
      "name": "Terbium",
      "nameOrigin": "Named after the Swedish town of Ytterby",
      "period": 6,
      "periodTableBlock": "f",
      "radiusVDW": 2.37,
      "symbol": "Tb"
    }, {
      "atomicNumber": 66,
      "boilingpoint": 2840.0,
      "discoverers": "F. E. Lecoq de Boisbaudran",
      "discoveryDate": "1886",
      "electronAffinity": 0.5,
      "electronegativityPauling": 1.22,
      "electronicConfiguration": "Xe 4f10 6s2",
      "elementColor": [0.12, 1.0, 0.78],
      "exactMass": 163.9291748,
      "family": "Rare_Earth",
      "group": 2,
      "ionization": 5.9389,
      "mass": 162.5,
      "meltingpoint": 1685.0,
      "name": "Dysprosium",
      "nameOrigin": "Greek 'dysprositor' for 'difficult to reach'",
      "period": 6,
      "periodTableBlock": "f",
      "radiusVDW": 2.35,
      "symbol": "Dy"
    }, {
      "atomicNumber": 67,
      "boilingpoint": 2968.0,
      "discoverers": ["J. L. Soret", "P.T. Cleve"],
      "discoveryDate": "1878",
      "electronAffinity": 0.5,
      "electronegativityPauling": 1.23,
      "electronicConfiguration": "Xe 4f11 6s2",
      "elementColor": [0.0, 1.0, 0.61],
      "exactMass": 164.9303221,
      "family": "Rare_Earth",
      "group": 3,
      "ionization": 6.0215,
      "mass": 164.93032,
      "meltingpoint": 1747.0,
      "name": "Holmium",
      "nameOrigin": "Latin 'holmia' for the old name of Stockholm",
      "period": 6,
      "periodTableBlock": "f",
      "radiusVDW": 2.33,
      "symbol": "Ho"
    }, {
      "atomicNumber": 68,
      "boilingpoint": 3140.0,
      "discoverers": "K. G. Mosander",
      "discoveryDate": "1843",
      "electronAffinity": 0.5,
      "electronegativityPauling": 1.24,
      "electronicConfiguration": "Xe 4f12 6s2",
      "elementColor": [0.0, 0.9, 0.46],
      "exactMass": 165.9302931,
      "family": "Rare_Earth",
      "group": 4,
      "ionization": 6.1077,
      "mass": 167.259,
      "meltingpoint": 1802.0,
      "name": "Erbium",
      "nameOrigin": "Named ofter the Swedish town of Ytterby. Terbium and Ytterbium are also named after this town.",
      "period": 6,
      "periodTableBlock": "f",
      "radiusVDW": 2.32,
      "symbol": "Er"
    }, {
      "atomicNumber": 69,
      "boilingpoint": 2223.0,
      "discoverers": "P. T. Cleve",
      "discoveryDate": "1879",
      "electronAffinity": 0.5,
      "electronegativityPauling": 1.25,
      "electronicConfiguration": "Xe 4f13 6s2",
      "elementColor": [0.0, 0.83, 0.32],
      "exactMass": 168.9342133,
      "family": "Rare_Earth",
      "group": 5,
      "ionization": 6.1843,
      "mass": 168.93421,
      "meltingpoint": 1818.0,
      "name": "Thulium",
      "nameOrigin": "Named after the old name of Scandinavia, 'Thule'.",
      "period": 6,
      "periodTableBlock": "f",
      "radiusVDW": 2.3,
      "symbol": "Tm"
    }, {
      "atomicNumber": 70,
      "boilingpoint": 1469.0,
      "discoverers": "J. Ch. Marignac",
      "discoveryDate": "1878",
      "electronAffinity": 0.5,
      "electronicConfiguration": "Xe 4f14 6s2",
      "elementColor": [0.0, 0.75, 0.22],
      "exactMass": 173.9388621,
      "family": "Rare_Earth",
      "group": 6,
      "ionization": 6.2542,
      "mass": 173.054,
      "meltingpoint": 1092.0,
      "name": "Ytterbium",
      "nameOrigin": "Like Terbium and Gadolinium, this is named after the Swedish town of Ytterby.",
      "period": 6,
      "periodTableBlock": "f",
      "radiusVDW": 2.28,
      "symbol": "Yb"
    }, {
      "atomicNumber": 71,
      "boilingpoint": 3668.0,
      "discoverers": ["Carl F. Auer von Welsbach", "G. Urbain"],
      "discoveryDate": "1907",
      "electronAffinity": 0.5,
      "electronegativityPauling": 1.27,
      "electronicConfiguration": "Xe 4f14 5d1 6s2",
      "elementColor": [0.0, 0.67, 0.14],
      "exactMass": 174.9407718,
      "family": "Rare_Earth",
      "group": 7,
      "ionization": 5.4259,
      "mass": 174.9668,
      "meltingpoint": 1936.0,
      "name": "Lutetium",
      "nameOrigin": "Named after the Roman name 'Lutetia' for Paris",
      "period": 6,
      "periodTableBlock": "f",
      "radiusCovalent": 1.6,
      "radiusVDW": 2.27,
      "symbol": "Lu"
    }, {
      "atomicNumber": 72,
      "boilingpoint": 4875.0,
      "discoverers": ["D. Coster", "G. Hevesy"],
      "discoveryCountry": "dk",
      "discoveryDate": "1923",
      "electronAffinity": 0.0,
      "electronegativityPauling": 1.3,
      "electronicConfiguration": "Xe 4f14 5d2 6s2",
      "elementColor": [0.3, 0.76, 1.0],
      "exactMass": 179.94655,
      "family": "Transition",
      "group": 4,
      "ionization": 6.8251,
      "mass": 178.49,
      "meltingpoint": 2504.0,
      "name": "Hafnium",
      "nameOrigin": "'Hafnia' is the old name of Kopenhagen (Denmark)",
      "period": 6,
      "periodTableBlock": "d",
      "radiusCovalent": 1.5,
      "radiusVDW": 2.25,
      "symbol": "Hf"
    }, {
      "atomicNumber": 73,
      "boilingpoint": 5730.0,
      "discoverers": "A. Ekeberg",
      "discoveryCountry": "se",
      "discoveryDate": "1802",
      "electronAffinity": 0.322,
      "electronegativityPauling": 1.5,
      "electronicConfiguration": "Xe 4f14 5d3 6s2",
      "elementColor": [0.3, 0.65, 1.0],
      "exactMass": 180.9479958,
      "family": "Transition",
      "group": 5,
      "ionization": 7.5496,
      "mass": 180.94788,
      "meltingpoint": 3293.0,
      "name": "Tantalum",
      "nameOrigin": "Named after the Greek myth of Tantalos",
      "period": 6,
      "periodTableBlock": "d",
      "radiusCovalent": 1.38,
      "radiusVDW": 2.2,
      "symbol": "Ta"
    }, {
      "atomicNumber": 74,
      "boilingpoint": 5825.0,
      "discoverers": "C. W. Scheele",
      "discoveryCountry": "es",
      "discoveryDate": "1783",
      "electronAffinity": 0.815,
      "electronegativityPauling": 2.36,
      "electronicConfiguration": "Xe 4f14 5d4 6s2",
      "elementColor": [0.13, 0.58, 0.84],
      "exactMass": 183.9509312,
      "family": "Transition",
      "group": 6,
      "ionization": 7.864,
      "mass": 183.84,
      "meltingpoint": 3695.0,
      "name": "Tungsten",
      "nameOrigin": "'tung sten' means 'heavy stone' in Swedish. The old name (and thus the symbol 'W') was Wolfram, named after a mineral.",
      "period": 6,
      "periodTableBlock": "d",
      "radiusCovalent": 1.46,
      "radiusVDW": 2.1,
      "symbol": "W"
    }, {
      "atomicNumber": 75,
      "boilingpoint": 5870.0,
      "discoverers": ["Walter Noddack", "Ida Tacke-Noddack", "Otto Berg"],
      "discoveryCountry": "de",
      "discoveryDate": "1925",
      "electronAffinity": 0.15,
      "electronegativityPauling": 1.9,
      "electronicConfiguration": "Xe 4f14 5d5 6s2",
      "elementColor": [0.15, 0.49, 0.67],
      "exactMass": 186.9557531,
      "family": "Transition",
      "group": 7,
      "ionization": 7.8335,
      "mass": 186.207,
      "meltingpoint": 3455.0,
      "name": "Rhenium",
      "nameOrigin": "Named after the German river Rhine (latin 'Rhenium').",
      "period": 6,
      "periodTableBlock": "d",
      "radiusCovalent": 1.59,
      "radiusVDW": 2.05,
      "symbol": "Re"
    }, {
      "atomicNumber": 76,
      "boilingpoint": 5300.0,
      "discoverers": "S. Tennant",
      "discoveryCountry": "uk",
      "discoveryDate": "1804",
      "electronAffinity": 1.0778,
      "electronegativityPauling": 2.2,
      "electronicConfiguration": "Xe 4f14 5d6 6s2",
      "elementColor": [0.15, 0.4, 0.59],
      "exactMass": 191.9614807,
      "family": "Transition",
      "group": 8,
      "ionization": 8.4382,
      "mass": 190.23,
      "meltingpoint": 3300.0,
      "name": "Osmium",
      "nameOrigin": "Greek for 'smell'. Its oxides smell strongly like radishes.",
      "period": 6,
      "periodTableBlock": "d",
      "radiusCovalent": 1.28,
      "radiusVDW": 2.0,
      "symbol": "Os"
    }, {
      "atomicNumber": 77,
      "boilingpoint": 4700.0,
      "discoverers": "S. Tennant",
      "discoveryCountry": "uk",
      "discoveryDate": "1804",
      "electronAffinity": 1.56436,
      "electronegativityPauling": 2.2,
      "electronicConfiguration": "Xe 4f14 5d7 6s2",
      "elementColor": [0.09, 0.33, 0.53],
      "exactMass": 192.9629264,
      "family": "Transition",
      "group": 8,
      "ionization": 8.967,
      "mass": 192.217,
      "meltingpoint": 2720.0,
      "name": "Iridium",
      "nameOrigin": "Greek 'iris' for 'rainbow'",
      "period": 6,
      "periodTableBlock": "d",
      "radiusCovalent": 1.37,
      "radiusVDW": 2.0,
      "symbol": "Ir"
    }, {
      "atomicNumber": 78,
      "boilingpoint": 4100.0,
      "discoverers": "A. de Ulloa",
      "discoveryCountry": "uk",
      "discoveryDate": "1735",
      "electronAffinity": 2.1251,
      "electronegativityPauling": 2.28,
      "electronicConfiguration": "Xe 4f14 5d9 6s1",
      "elementColor": [0.96, 0.93, 0.82],
      "exactMass": 194.9647911,
      "family": "Transition",
      "group": 8,
      "ionization": 8.9588,
      "mass": 195.084,
      "meltingpoint": 2042.1,
      "name": "Platinum",
      "nameOrigin": "Spanish 'platina' means 'small silver'",
      "period": 6,
      "periodTableBlock": "d",
      "radiusCovalent": 1.28,
      "radiusVDW": 2.05,
      "symbol": "Pt"
    }, {
      "atomicNumber": 79,
      "boilingpoint": 3130.0,
      "discoveryCountry": "ancient",
      "discoveryDate": "0",
      "electronAffinity": 2.30861,
      "electronegativityPauling": 2.54,
      "electronicConfiguration": "Xe 4f14 5d10 6s1",
      "elementColor": [0.8, 0.82, 0.12],
      "exactMass": 196.9665687,
      "family": "Transition",
      "group": 1,
      "ionization": 9.2255,
      "mass": 196.966569,
      "meltingpoint": 1337.58,
      "name": "Gold",
      "nameOrigin": "Latin 'aurum'. Named after Aurora, the goddess of sunrise",
      "period": 6,
      "periodTableBlock": "d",
      "radiusCovalent": 1.44,
      "radiusVDW": 2.1,
      "symbol": "Au"
    }, {
      "atomicNumber": 80,
      "boilingpoint": 629.88,
      "discoveryCountry": "ancient",
      "discoveryDate": "0",
      "electronAffinity": 0.0,
      "electronegativityPauling": 2.0,
      "electronicConfiguration": "Xe 4f14 5d10 6s2",
      "elementColor": [0.71, 0.71, 0.76],
      "exactMass": 201.970643,
      "family": "Transition",
      "group": 2,
      "ionization": 10.4375,
      "mass": 200.59,
      "meltingpoint": 234.31,
      "name": "Mercury",
      "nameOrigin": "Graeco-Latin 'hydrargyrum' for 'liquid silver'",
      "period": 6,
      "periodTableBlock": "d",
      "radiusCovalent": 1.49,
      "radiusVDW": 2.05,
      "symbol": "Hg"
    }, {
      "atomicNumber": 81,
      "boilingpoint": 1746.0,
      "discoverers": "W. Crookes",
      "discoveryCountry": "uk",
      "discoveryDate": "1861",
      "electronAffinity": 0.377,
      "electronegativityPauling": 1.62,
      "electronicConfiguration": "Xe 4f14 5d10 6s2 6p1",
      "elementColor": [0.65, 0.33, 0.3],
      "exactMass": 204.9744275,
      "family": "Other_Metal",
      "group": 3,
      "ionization": 6.1082,
      "mass": 204.3833,
      "meltingpoint": 577.0,
      "name": "Thallium",
      "nameOrigin": "Greek 'tallos' for 'young twig'",
      "period": 6,
      "periodTableBlock": "p",
      "radiusCovalent": 1.48,
      "radiusVDW": 2.2,
      "symbol": "Tl"
    }, {
      "atomicNumber": 82,
      "boilingpoint": 2023.0,
      "discoveryCountry": "ancient",
      "discoveryDate": "0",
      "electronAffinity": 0.364,
      "electronegativityPauling": 2.33,
      "electronicConfiguration": "Xe 4f14 5d10 6s2 6p2",
      "elementColor": [0.34, 0.35, 0.38],
      "exactMass": 207.9766521,
      "family": "Other_Metal",
      "group": 4,
      "ionization": 7.4167,
      "mass": 207.2,
      "meltingpoint": 600.65,
      "name": "Lead",
      "nameOrigin": "Latin 'plumbum' for Lead",
      "period": 6,
      "periodTableBlock": "p",
      "radiusCovalent": 1.47,
      "radiusVDW": 2.3,
      "symbol": "Pb"
    }, {
      "atomicNumber": 83,
      "boilingpoint": 1837.0,
      "discoveryCountry": "ancient",
      "discoveryDate": "0",
      "electronAffinity": 0.942363,
      "electronegativityPauling": 2.02,
      "electronicConfiguration": "Xe 4f14 5d10 6s2 6p3",
      "elementColor": [0.62, 0.31, 0.71],
      "exactMass": 208.9803987,
      "family": "Other_Metal",
      "group": 5,
      "ionization": 7.2855,
      "mass": 208.9804,
      "meltingpoint": 544.59,
      "name": "Bismuth",
      "nameOrigin": "The old name of Bismuth is 'Wismut', which stood for 'white mass'.",
      "period": 6,
      "periodTableBlock": "p",
      "radiusCovalent": 1.46,
      "radiusVDW": 2.3,
      "symbol": "Bi"
    }, {
      "atomicNumber": 84,
      "discoverers": ["M. Sklodowska-Curie", "P. Curie"],
      "discoveryCountry": "fr",
      "discoveryDate": "1898",
      "electronAffinity": 1.9,
      "electronegativityPauling": 2.0,
      "electronicConfiguration": "Xe 4f14 5d10 6s2 6p4",
      "elementColor": [0.67, 0.36, 0.0],
      "exactMass": 208.9824304,
      "family": "Metalloids",
      "group": 6,
      "ionization": 8.414,
      "mass": 209.0,
      "meltingpoint": 527.0,
      "name": "Polonium",
      "nameOrigin": "Named after Poland to honor Marie Curie",
      "period": 6,
      "periodTableBlock": "p",
      "radiusVDW": 2.0,
      "symbol": "Po"
    }, {
      "atomicNumber": 85,
      "boilingpoint": 610.0,
      "discoverers": ["D. R. Corson", "K. R. McKenzie", "E. Segre"],
      "discoveryCountry": "us",
      "discoveryDate": "1940",
      "electronAffinity": 2.8,
      "electronegativityPauling": 2.2,
      "electronicConfiguration": "Xe 4f14 5d10 6s2 6p5",
      "elementColor": [0.46, 0.31, 0.27],
      "exactMass": 209.987148,
      "family": "Halogen",
      "group": 7,
      "ionization": 0.0,
      "mass": 210.0,
      "meltingpoint": 575.0,
      "name": "Astatine",
      "nameOrigin": "Greek 'astator' for 'changing'",
      "period": 6,
      "periodTableBlock": "p",
      "radiusVDW": 2.0,
      "symbol": "At"
    }, {
      "atomicNumber": 86,
      "boilingpoint": 211.4,
      "discoverers": "E. Dorn",
      "discoveryCountry": "de",
      "discoveryDate": "1898",
      "electronAffinity": 0.0,
      "electronicConfiguration": "Xe 4f14 5d10 6s2 6p6",
      "elementColor": [0.26, 0.51, 0.59],
      "exactMass": 222.0175777,
      "family": "Noblegas",
      "group": 8,
      "ionization": 10.7485,
      "mass": 222.0,
      "meltingpoint": 202.0,
      "name": "Radon",
      "nameOrigin": "Named after Radium. It ends with 'on' to make it clear that it is a noble gas.",
      "period": 6,
      "periodTableBlock": "p",
      "radiusCovalent": 1.45,
      "radiusVDW": 2.0,
      "symbol": "Rn"
    }, {
      "atomicNumber": 87,
      "boilingpoint": 950.0,
      "discoverers": "M. Perey",
      "discoveryCountry": "fr",
      "discoveryDate": "1939",
      "electronegativityPauling": 0.7,
      "electronicConfiguration": "Rn 7s1",
      "elementColor": [0.26, 0.0, 0.4],
      "exactMass": 223.0197359,
      "family": "Alkali_Earth",
      "group": 1,
      "ionization": 4.0727,
      "mass": 223.0,
      "meltingpoint": 300.0,
      "name": "Francium",
      "nameOrigin": "Named after France to honor Marguerite Perey",
      "period": 7,
      "periodTableBlock": "s",
      "radiusVDW": 2.0,
      "symbol": "Fr"
    }, {
      "atomicNumber": 88,
      "boilingpoint": 1413.0,
      "discoverers": ["M. Sklodowska-Curie", "P. Curie"],
      "discoveryCountry": "fr",
      "discoveryDate": "1898",
      "electronegativityPauling": 0.9,
      "electronicConfiguration": "Rn 7s2",
      "elementColor": [0.0, 0.49, 0.0],
      "exactMass": 226.0254098,
      "family": "Alkaline_Earth",
      "group": 2,
      "ionization": 5.2784,
      "mass": 226.0,
      "meltingpoint": 973.0,
      "name": "Radium",
      "nameOrigin": "Latin 'radius' for 'beam', as it is radioactive",
      "period": 7,
      "periodTableBlock": "s",
      "radiusVDW": 2.0,
      "symbol": "Ra"
    }, {
      "atomicNumber": 89,
      "boilingpoint": 3470.0,
      "discoverers": "A. L. Debierne",
      "discoveryCountry": "fr",
      "discoveryDate": "1899",
      "electronegativityPauling": 1.1,
      "electronicConfiguration": "Rn 6d1 7s2",
      "elementColor": [0.44, 0.67, 0.98],
      "exactMass": 227.0277521,
      "family": "Other_Metal",
      "group": 3,
      "ionization": 5.17,
      "mass": 227.0,
      "meltingpoint": 1324.0,
      "name": "Actinium",
      "nameOrigin": "Greek 'aktis' for 'beam' - actinium is radioactive",
      "period": 7,
      "periodTableBlock": "f",
      "radiusVDW": 2.0,
      "symbol": "Ac"
    }, {
      "atomicNumber": 90,
      "boilingpoint": 5060.0,
      "discoverers": "J. J. Berzelius",
      "discoveryDate": "1828",
      "electronegativityPauling": 1.3,
      "electronicConfiguration": "Rn 6d2 7s2",
      "elementColor": [0.0, 0.73, 1.0],
      "exactMass": 232.0380553,
      "family": "Other_Metal",
      "group": 4,
      "ionization": 6.3067,
      "mass": 232.03806,
      "meltingpoint": 2028.0,
      "name": "Thorium",
      "nameOrigin": "Named after the German god of thunder: Thor",
      "period": 7,
      "periodTableBlock": "f",
      "radiusVDW": 2.4,
      "symbol": "Th"
    }, {
      "atomicNumber": 91,
      "boilingpoint": 4300.0,
      "discoverers": ["O. Hahn", "L. Meitern", "W. Wollaston"],
      "discoveryDate": "1917",
      "electronegativityPauling": 1.5,
      "electronicConfiguration": "Rn 5f2 6d1 7s2",
      "elementColor": [0.0, 0.63, 1.0],
      "exactMass": 231.035884,
      "family": "Other_Metal",
      "group": 5,
      "ionization": 5.89,
      "mass": 231.03588,
      "meltingpoint": 1845.0,
      "name": "Protactinium",
      "nameOrigin": "Greek 'protos' for 'ancester'. Protactinium is before Actinium in the periodic table.",
      "period": 7,
      "periodTableBlock": "f",
      "radiusVDW": 2.0,
      "symbol": "Pa"
    }, {
      "atomicNumber": 92,
      "boilingpoint": 4407.0,
      "discoverers": "M. M. Klaproth",
      "discoveryDate": "1789",
      "electronegativityPauling": 1.38,
      "electronicConfiguration": "Rn 5f3 6d1 7s2",
      "elementColor": [0.0, 0.56, 1.0],
      "exactMass": 238.0507882,
      "family": "Other_Metal",
      "group": 6,
      "ionization": 6.1941,
      "mass": 238.02891,
      "meltingpoint": 1408.0,
      "name": "Uranium",
      "nameOrigin": "Greek 'ouranos' for 'heaven'. Named after the planet Uranus.",
      "period": 7,
      "periodTableBlock": "f",
      "radiusVDW": 2.3,
      "symbol": "U"
    }, {
      "atomicNumber": 93,
      "boilingpoint": 4175.0,
      "discoverers": ["E. M. McMillan", "P. Aberson"],
      "discoveryDate": "1940",
      "electronegativityPauling": 1.36,
      "electronicConfiguration": "Rn 5f4 6d1 7s2",
      "elementColor": [0.0, 0.5, 1.0],
      "exactMass": 237.0481734,
      "family": "Other_Metal",
      "group": 7,
      "ionization": 6.2657,
      "mass": 237.0,
      "meltingpoint": 912.0,
      "name": "Neptunium",
      "nameOrigin": "Named after the planet Neptune.",
      "period": 7,
      "periodTableBlock": "f",
      "radiusVDW": 2.0,
      "symbol": "Np"
    }, {
      "atomicNumber": 94,
      "boilingpoint": 3505.0,
      "discoverers": ["Glenn T. Seaborg", "E. M. McMillan", "J. W. Kennedy", "A.C. Wahl"],
      "discoveryDate": "1940",
      "electronegativityPauling": 1.28,
      "electronicConfiguration": "Rn 5f6 7s2",
      "elementColor": [0.0, 0.42, 1.0],
      "exactMass": 244.064204,
      "family": "Other_Metal",
      "group": 8,
      "ionization": 6.026,
      "mass": 244.0,
      "meltingpoint": 913.0,
      "name": "Plutonium",
      "nameOrigin": "Named after the planet Pluto.",
      "period": 7,
      "periodTableBlock": "f",
      "radiusVDW": 2.0,
      "symbol": "Pu"
    }, {
      "atomicNumber": 95,
      "boilingpoint": 2880.0,
      "discoverers": ["Glenn T. Seaborg", "L. O. Morgan", "R. A. James", "A. Ghiors"],
      "discoveryDate": "1945",
      "electronegativityPauling": 1.3,
      "electronicConfiguration": "Rn 5f7 7s2",
      "elementColor": [0.33, 0.36, 0.95],
      "exactMass": 243.0613811,
      "family": "Other_Metal",
      "group": 8,
      "ionization": 5.9738,
      "mass": 243.0,
      "meltingpoint": 1449.0,
      "name": "Americium",
      "nameOrigin": "Named after America.",
      "period": 7,
      "periodTableBlock": "f",
      "radiusVDW": 2.0,
      "symbol": "Am"
    }, {
      "atomicNumber": 96,
      "boilingpoint": 3383.0,
      "discoverers": ["Glenn T. Seaborg", "R. A. James", "A. Ghiors"],
      "discoveryDate": "1944",
      "electronegativityPauling": 1.3,
      "electronicConfiguration": "Rn 5f7 6d1 7s2",
      "elementColor": [0.47, 0.36, 0.89],
      "exactMass": 247.070354,
      "family": "Other_Metal",
      "group": 8,
      "ionization": 5.9914,
      "mass": 247.0,
      "meltingpoint": 1620.0,
      "name": "Curium",
      "nameOrigin": "Named after Marie Curie.",
      "period": 7,
      "periodTableBlock": "f",
      "radiusVDW": 2.0,
      "symbol": "Cm"
    }, {
      "atomicNumber": 97,
      "boilingpoint": 983.0,
      "discoverers": ["Glenn T. Seaborg", "A. Ghiors", "S. G. Thompson"],
      "discoveryDate": "1949",
      "electronegativityPauling": 1.3,
      "electronicConfiguration": "Rn 5f9 7s2",
      "elementColor": [0.54, 0.31, 0.89],
      "exactMass": 247.070307,
      "family": "Other_Metal",
      "group": 1,
      "ionization": 6.1979,
      "mass": 247.0,
      "meltingpoint": 1258.0,
      "name": "Berkelium",
      "nameOrigin": "Named after the town Berkeley where it was discovered.",
      "period": 7,
      "periodTableBlock": "f",
      "radiusVDW": 2.0,
      "symbol": "Bk"
    }, {
      "atomicNumber": 98,
      "boilingpoint": 1173.0,
      "discoverers": ["Glenn T. Seaborg", "A. Ghiors", "S. G. Thompson"],
      "discoveryDate": "1950",
      "electronegativityPauling": 1.3,
      "electronicConfiguration": "Rn 5f10 7s2",
      "elementColor": [0.63, 0.21, 0.83],
      "exactMass": 251.079587,
      "family": "Other_Metal",
      "group": 2,
      "ionization": 6.2817,
      "mass": 251.0,
      "meltingpoint": 1172.0,
      "name": "Californium",
      "nameOrigin": "Named after the US-State of California.",
      "period": 7,
      "periodTableBlock": "f",
      "radiusVDW": 2.0,
      "symbol": "Cf"
    }, {
      "atomicNumber": 99,
      "discoverers": ["Glenn T. Seaborg", "et al."],
      "discoveryDate": "1952",
      "electronegativityPauling": 1.3,
      "electronicConfiguration": "Rn 5f11 7s2",
      "elementColor": [0.7, 0.12, 0.83],
      "exactMass": 252.08298,
      "family": "Other_Metal",
      "group": 3,
      "ionization": 6.42,
      "mass": 252.0,
      "meltingpoint": 1130.0,
      "name": "Einsteinium",
      "nameOrigin": "Named after the scientist Albert Einstein.",
      "period": 7,
      "periodTableBlock": "f",
      "radiusVDW": 2.0,
      "symbol": "Es"
    }, {
      "atomicNumber": 100,
      "discoverers": ["Glenn T. Seaborg", "et al."],
      "discoveryDate": "1953",
      "electronegativityPauling": 1.3,
      "electronicConfiguration": "Rn 5f12 7s2",
      "elementColor": [0.7, 0.12, 0.73],
      "exactMass": 257.095105,
      "family": "Other_Metal",
      "group": 4,
      "ionization": 6.5,
      "mass": 257.0,
      "meltingpoint": 1800.0,
      "name": "Fermium",
      "nameOrigin": "Named after the scientist Enrico Fermi.",
      "period": 7,
      "periodTableBlock": "f",
      "radiusVDW": 2.0,
      "symbol": "Fm"
    }, {
      "atomicNumber": 101,
      "discoverers": ["Glenn T. Seaborg", "Albert Ghiorso", "Bernard Harvey", "Gregory Choppin", "Stanley G. Thompson"],
      "discoveryDate": "1955",
      "electronegativityPauling": 1.3,
      "electronicConfiguration": "Rn 5f13 7s2",
      "elementColor": [0.7, 0.05, 0.65],
      "exactMass": 258.098431,
      "family": "Other_Metal",
      "group": 5,
      "ionization": 6.58,
      "mass": 258.0,
      "meltingpoint": 1100.0,
      "name": "Mendelevium",
      "nameOrigin": "Named after the scientist D.I. Mendeleev.",
      "period": 7,
      "periodTableBlock": "f",
      "radiusVDW": 2.0,
      "symbol": "Md"
    }, {
      "atomicNumber": 102,
      "discoveryDate": "1958",
      "electronegativityPauling": 1.3,
      "electronicConfiguration": "Rn 5f14 7s2",
      "elementColor": [0.74, 0.05, 0.53],
      "exactMass": 259.10103,
      "family": "Other_Metal",
      "group": 6,
      "ionization": 6.65,
      "mass": 259.0,
      "meltingpoint": 1100.0,
      "name": "Nobelium",
      "nameOrigin": "Named after the scientist Alfred Nobel.",
      "period": 7,
      "periodTableBlock": "f",
      "radiusVDW": 2.0,
      "symbol": "No"
    }, {
      "atomicNumber": 103,
      "discoverers": ["Albert Ghiorso", "Torbjorn Sikkeland", "Almon Larsh", "Robert M. Latimer"],
      "discoveryDate": "1961",
      "electronicConfiguration": "Rn 5f14 7s2 7p1",
      "elementColor": [0.78, 0.0, 0.4],
      "exactMass": 262.10963,
      "family": "Other_Metal",
      "group": 7,
      "ionization": 4.9,
      "mass": 262.0,
      "meltingpoint": 1900.0,
      "name": "Lawrencium",
      "nameOrigin": "Named after the scientist Ernest Orlando Lawrence.",
      "period": 7,
      "periodTableBlock": "f",
      "radiusVDW": 2.0,
      "symbol": "Lr"
    }, {
      "atomicNumber": 104,
      "discoveryCountry": ["ru", "us"],
      "discoveryDate": "1964",
      "electronicConfiguration": "Rn 5f14 6d2 7s2",
      "elementColor": [0.8, 0.0, 0.35],
      "exactMass": 261.10877,
      "family": "Transition",
      "group": 4,
      "ionization": 6.0,
      "mass": 267.0,
      "name": "Rutherfordium",
      "nameOrigin": "Named after the scientist Ernest Rutherford",
      "period": 7,
      "periodTableBlock": "d",
      "radiusVDW": 2.0,
      "symbol": "Rf"
    }, {
      "atomicNumber": 105,
      "discoveryCountry": ["ru", "us"],
      "discoveryDate": "1967",
      "electronicConfiguration": "Rn 5f14 6d3 7s2",
      "elementColor": [0.82, 0.0, 0.31],
      "exactMass": 262.11408,
      "family": "Transition",
      "group": 5,
      "mass": 268.0,
      "name": "Dubnium",
      "nameOrigin": "Named after the science-town Dubna in Russia",
      "period": 7,
      "periodTableBlock": "d",
      "radiusVDW": 2.0,
      "symbol": "Db"
    }, {
      "atomicNumber": 106,
      "discoverers": ["Albert Ghiorso", "et al."],
      "discoveryCountry": ["ru", "us"],
      "discoveryDate": "1974",
      "elementColor": [0.85, 0.0, 0.27],
      "exactMass": 263.11832,
      "family": "Transition",
      "group": 6,
      "mass": 271.0,
      "name": "Seaborgium",
      "nameOrigin": "Named after the scientist G. Theodore Seaborg.",
      "period": 7,
      "periodTableBlock": "d",
      "radiusVDW": 2.0,
      "symbol": "Sg"
    }, {
      "atomicNumber": 107,
      "discoverers": ["Peter Armbruster", "Gottfried M\u00fcnzenber", "et al."],
      "discoveryCountry": "ru",
      "discoveryDate": "1981",
      "elementColor": [0.88, 0.0, 0.22],
      "exactMass": 264.1246,
      "family": "Transition",
      "group": 7,
      "mass": 272.0,
      "name": "Bohrium",
      "nameOrigin": "Named after the scientist Niels Bohr.",
      "period": 7,
      "periodTableBlock": "d",
      "radiusVDW": 2.0,
      "symbol": "Bh"
    }, {
      "atomicNumber": 108,
      "discoverers": ["Peter Armbruster", "Gottfried M\u00fcnzenber", "et al."],
      "discoveryCountry": "de",
      "discoveryDate": "1984",
      "elementColor": [0.9, 0.0, 0.18],
      "exactMass": 265.13009,
      "family": "Transition",
      "group": 8,
      "mass": 270.0,
      "name": "Hassium",
      "nameOrigin": "Latin 'hassia' for the German county Hessen. In Hessen a lot elements have been discovered.",
      "period": 7,
      "periodTableBlock": "d",
      "radiusVDW": 2.0,
      "symbol": "Hs"
    }, {
      "atomicNumber": 109,
      "discoverers": ["Peter Armbruster", "Gottfried M\u00fcnzenber", "et al."],
      "discoveryCountry": "de",
      "discoveryDate": "1982",
      "elementColor": [0.91, 0.0, 0.15],
      "exactMass": 268.13873,
      "family": "Transition",
      "group": 8,
      "mass": 276.0,
      "name": "Meitnerium",
      "nameOrigin": "Named after the scientist Lise Meitner.",
      "period": 7,
      "periodTableBlock": "d",
      "radiusVDW": 2.0,
      "symbol": "Mt"
    }, {
      "atomicNumber": 110,
      "discoverers": ["S. Hofmann", "V. Ninov", "F. P. Hessberger", "P. Armbruster", "H. Folger", "G. M\u00fcnzenberg",
        "H. J. Sch\u00f6tt", "et al."],
      "discoveryCountry": "de",
      "discoveryDate": "1994",
      "elementColor": [0.92, 0.0, 0.14],
      "exactMass": 271.14606,
      "family": "Transition",
      "group": 8,
      "mass": 281.0,
      "name": "Darmstadtium",
      "nameOrigin": "Named after the German city Darmstadt where many elements have been discovered.",
      "period": 7,
      "periodTableBlock": "d",
      "symbol": "Ds"
    }, {
      "atomicNumber": 111,
      "discoverers": ["S. Hofmann", "V. Ninov", "F. P. Hessberger", "P. Armbruster", "H. Folger", "G. M\u00fcnzenberg",
        "et al."],
      "discoveryCountry": "de",
      "discoveryDate": "1994",
      "elementColor": [0.93, 0.0, 0.13],
      "exactMass": 272.15362,
      "family": "Transition",
      "group": 1,
      "mass": 280.0,
      "name": "Roentgenium",
      "nameOrigin": "Named after Wilhelm Conrad R\u00f6ntgen.",
      "period": 7,
      "periodTableBlock": "d",
      "symbol": "Rg"
    }, {
      "atomicNumber": 112,
      "discoverers": "First created at the Gesellschaft f\u00fcr Schwerionenforschung",
      "discoveryCountry": "de",
      "discoveryDate": "1996",
      "elementColor": [0.94, 0.0, 0.12],
      "exactMass": 285.17411,
      "family": "Transition",
      "mass": 285.0,
      "name": "Copernicium",
      "nameOrigin": "Historically known as eka-mercury. Ununbium is a temporary IUPAC systematic element name.",
      "period": 7,
      "periodTableBlock": "d",
      "symbol": "Cn"
    }, {
      "atomicNumber": 113,
      "discoverers": ["Russian scientists at Dubna (JINR)",
        "American scientists at the Lawrence Livermore National Laboratory."],
      "discoveryCountry": ["ru", "us"],
      "discoveryDate": "2003",
      "elementColor": [0.95, 0.0, 0.11],
      "exactMass": 284.17808,
      "family": "Other_Metal",
      "mass": 284.0,
      "name": "Ununtrium",
      "nameOrigin": "Historically known as eka-thallium. Ununtrium is a temporary IUPAC systematic element name.",
      "period": 7,
      "periodTableBlock": "p",
      "symbol": "Uut"
    }, {
      "atomicNumber": 114,
      "discoverers": "Joint Institute for Nuclear Research",
      "discoveryCountry": ["ru", "us"],
      "discoveryDate": "1998",
      "elementColor": [0.96, 0.0, 0.1],
      "exactMass": 289.18728,
      "family": "Other_Metal",
      "mass": 289.0,
      "name": "Ununquadium",
      "nameOrigin": "Historically known as eka-lead. Ununquadium is a temporary IUPAC systematic element name.",
      "period": 7,
      "periodTableBlock": "p",
      "symbol": "Uuq"
    }, {
      "atomicNumber": 115,
      "discoverers": ["Russian scientists at Dubna (JINR)",
        "American scientists at the Lawrence Livermore National Laboratory."],
      "discoveryCountry": ["ru", "us"],
      "discoveryDate": "2004",
      "elementColor": [0.97, 0.0, 0.09],
      "exactMass": 288.19249,
      "family": "Other_Metal",
      "mass": 288.0,
      "name": "Ununpentium",
      "nameOrigin": "Historically known as eka-bismuth. Ununpentium is a temporary IUPAC systematic element name.",
      "period": 7,
      "periodTableBlock": "p",
      "symbol": "Uup"
    }, {
      "atomicNumber": 116,
      "discoverers": "Joint Institute for Nuclear Research",
      "discoveryCountry": "ru",
      "discoveryDate": "2000",
      "elementColor": [0.98, 0.0, 0.08],
      "exactMass": 292.19979,
      "family": "Other_Metal",
      "mass": 293.0,
      "name": "Ununhexium",
      "nameOrigin": "Historically known as eka-polonium. Ununhexium is a temporary IUPAC systematic element name.",
      "period": 7,
      "periodTableBlock": "p",
      "symbol": "Uuh"
    }, {
      "atomicNumber": 117,
      "discoveryDate": "0",
      "elementColor": [0.99, 0.0, 0.07],
      "family": "Halogen",
      "name": "Ununseptium",
      "nameOrigin": "Temporary symbol and name. Can also be referred to as eka-astatine.",
      "period": 7,
      "periodTableBlock": "p",
      "symbol": "Uus"
    }, {
      "atomicNumber": 118,
      "discoverers": ["Russian scientists at Dubna (JINR)",
        "American scientists at the Lawrence Livermore National Laboratory."],
      "discoveryCountry": ["ru", "us"],
      "discoveryDate": "2002",
      "elementColor": [1.0, 0.0, 0.06],
      "family": "Noblegas",
      "mass": 294.0,
      "name": "Ununoctium",
      "nameOrigin": "Historically known as eka-radon, eka-emanation before 1960. Ununoctium is a temporary IUPAC systematic element name.",
      "period": 7,
      "periodTableBlock": "p",
      "symbol": "Uuo"
    }]
  }